
name: Build Mali build Driver
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Compile Driver
        run: ndk-build -C jni/ NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=jni/Android.mk APP_ABI=arm64-v8a

      - name: Create AdrenoTools Zip
        run: |
          mkdir -p package
          cp libs/arm64-v8a/vulkan.mt6768.so package/
          cp meta.json package/
          cd package && zip -r ../Mali-build-Driver.zip .

      - name: Upload Release
        uses: actions/upload-artifact@v4
        with:
          name: Mali-build-Zip
          path: Mali-build-Driver.zip
