name: Mali build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_driver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Build
        run: |
          ndk-build -C jni/ \
          NDK_PROJECT_PATH=. \
          APP_BUILD_SCRIPT=jni/Android.mk \
          APP_ABI=arm64-v8a

      - name: Zip
        run: |
          mkdir -p output
          cp libs/arm64-v8a/vulkan.mt6768.so output/
          cp meta.json output/
          cd output && zip -r ../Mali-build.zip .

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Mali-build-Zip
          path: Mali-build.zip
